# Configure main menu and social menu
[[main]]
identifier = "warehouse"
name = "Warehouse"
url = "/warehouse/"
[main.params]
icon = "warehouse"
newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/nqounet"

[social.params]
icon = "brand-github"

[[social]]
identifier = "x"
name = "X"
url = "https://x.com/nqounet"

[social.params]
icon = "brand-twitter"
